### ISSUE TITLE
npm not completely set up

### ISSUE THREAD

**Issue by rdfriedl** [wout/svg.filter.js#10]
sorry to keep bugging you about this library, but the package.json is not complete.
if i install `npm install svg.filter.js --save` and then use `require('svg.filter.js')` it fails because there is not `"main"` field in the package.json

thanks :D

**Comment by Fuzzyma** [comment]
Is it just `"main":"./dist/svg.filter.js"`?

**Comment by rdfriedl** [comment]
yes that should be it, the svg.js project has it in its package.json and it works fine

**Comment by Fuzzyma** [comment]
ok - that should do it

**Comment by rdfriedl** [comment]
oh sorry i did not mean set it to `dist/svg.js`
it has to point to the `dist/svg.filter.js` or `dist/svg.filter.min.js`
you dont have to fix it now, im sure your busy so when ever you get a chance.

**Comment by Fuzzyma** [comment]
lol - the copycat failed there -.-
