### ISSUE TITLE
Explain how to pre-create a filter

### ISSUE THREAD

**Issue by maix** [wout/svg.filter.js#5]
I just wanted to find out if something like this was possible:

```
effect = drawing.defs().filter(function(add) {
// ...
})

drawing.rect().filter(effect)
```

and turns out it is, cool! (Thanks for that :) )

I think it'd be cool to add this to the documentation, as I think that it is a rather common use case, and it's more efficient to just do `.filter(effect)` instead of recreating the same filter over and over. (Maybe it should even be shown as the prefered way?)

(This is an issue not a pull request because I don't really know where it's best to add this.)

**Comment by rdfriedl** [comment]
as far as im aware there are multiple ways to create a filter element.
you can use the standard way
```javascript
image.filter(function(add){
    //filter stuff goes here
    var color = add.flood('black');
    var offset = add.offset(x,y).in(color);
    var blur = add.gaussianBlur(3).in(offset);
    var merge = add.merge(blur,filter.source);
})
```

or you can create a filter that is not attached to any element
```javascript
var filter = new SVG.Filter(function(add){
    //filter stuff goes here
    var color = add.flood('black');
    var offset = add.offset(x,y).in(color);
    var blur = add.gaussianBlur(3).in(offset);
    var merge = add.merge(blur,filter.source);
})

//or you could add it here
var color = filter.flood('black');
var offset = filter.offset(x,y).in(color);
var blur = filter.gaussianBlur(3).in(offset);
var merge = filter.merge(blur,filter.source);
```

also when you call the <code>rect.filter(myFilter)</code> it will add `myFilter` to the the defs section of the svg

**Comment by maix** [comment]
Thanks - the `new SVG.Filter` way is more elegant than my `drawing.defs` way.

However: This bug is about adding this information to the documentation

**Comment by Fuzzyma** [comment]
This is no bug. Also this is the standard way of creating objects in
svg.js. I thought about it as basic knowledge but feel free to add that to
the documentation! :)

Marian <notifications@github.com> schrieb am Mo., 22.02.2016, 10:09:
